### ISSUE TITLE
Can not run, please help

### ISSUE THREAD

**Issue by Leadrive** [Maxwell-Yang-PDFTron/flutter-sample#1]
I Download and unzip the WebViewer package to flutter-sample path.

flutter run -d chrome

run message is:
````javascript
ReferenceError: WebViewer is not defined                                                                                                                       
    at <anonymous>:2:9                                                                                                                                         
    at HTMLElement.[dartx.append] (http://localhost:1872/dart_sdk.js:64409:31)                                                                                 
    at _engine.DomRenderer.new.append (http://localhost:1872/dart_sdk.js:145795:24)                                                                            
    at _engine.DomRenderer.new.renderScene (http://localhost:1872/dart_sdk.js:145768:14)                                                                       
    at _engine.EnginePlatformDispatcher.__.render (http://localhost:1872/dart_sdk.js:162722:29)                                                                
    at _engine.EngineSingletonFlutterWindow.new.render (http://localhost:1872/dart_sdk.js:133300:38)                                                           
    at view.RenderView.new.compositeFrame (http://localhost:1872/packages/flutter/src/rendering/layer.dart.lib.js:4918:23)                                     
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:1872/packages/flutter/src/rendering/layer.dart.lib.js:6107:25)                          
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:1872/packages/flutter/src/widgets/widget_span.dart.lib.js:50527:15)                     
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:1872/packages/flutter/src/rendering/layer.dart.lib.js:6067:12)   
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:1872/packages/flutter/src/scheduler/binding.dart.lib.js:760:9)             
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:1872/packages/flutter/src/scheduler/binding.dart.lib.js:728:37)                   
    at http://localhost:1872/packages/flutter/src/scheduler/binding.dart.lib.js:642:14                                                                         
    at internalCallback (http://localhost:1872/dart_sdk.js:24724:11)                                                                                           
````

If I press R key to refresh.
report message is:
````javascript
Performing hot restart...                                          260ms                                                                                         
Restarted application in 262ms.                                                                                                                                  
SyntaxError: Identifier 'canvas' has already been declared                                                                                                       
    at HTMLElement.[dartx.append] (http://localhost:1872/dart_sdk.js:64409:31)                                                                                   
    at _engine.DomRenderer.new.append (http://localhost:1872/dart_sdk.js:145795:24)                                                                              
    at _engine.DomRenderer.new.renderScene (http://localhost:1872/dart_sdk.js:145768:14)                                                                         
    at _engine.EnginePlatformDispatcher.__.render (http://localhost:1872/dart_sdk.js:162722:29)                                                                  
    at _engine.EngineSingletonFlutterWindow.new.render (http://localhost:1872/dart_sdk.js:133300:38)                                                             
    at view.RenderView.new.compositeFrame (http://localhost:1872/packages/flutter/src/rendering/layer.dart.lib.js:4918:23)                                       
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:1872/packages/flutter/src/rendering/layer.dart.lib.js:6107:25)                            
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:1872/packages/flutter/src/widgets/widget_span.dart.lib.js:50527:15)                       
    at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:1872/packages/flutter/src/rendering/layer.dart.lib.js:6067:12)     
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:1872/packages/flutter/src/scheduler/binding.dart.lib.js:760:9)               
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:1872/packages/flutter/src/scheduler/binding.dart.lib.js:728:37)                     
    at http://localhost:1872/packages/flutter/src/scheduler/binding.dart.lib.js:642:14                                                                           
    at internalCallback (http://localhost:1872/dart_sdk.js:24724:11)                                                                                             
````

**Comment by Maxwell-Yang-PDFTron** [comment]
Hi there, not sure what exactly causes the problem, since everything seems fine to me when I followed the steps in README. The error is indicating that the WebViewer package was not set up correctly. Can you check the locations of you WebViewer package and make sure it looks like this:

flutter-sample
- android
- ios
- lib
- ...
- WebViewer (as a folder)
- web
- ...

**Comment by Leadrive** [comment]
Thank you.
Unzip to WebViewer folder, it will work fine.

I want to know how to support desktop?
Flutter support windows/linux/macos now.
https://flutter.dev/desktop

**Comment by Maxwell-Yang-PDFTron** [comment]
Sorry, currently we do not plan on adding support to desktop associated with Flutter.
